#!/usr/bin/env sh

# =============================================================================
# nlp-unconstrained-core/hooke-jeeves/java/bin/hooke-woods
# =============================================================================
# Nonlinear Optimization Algorithms Multilang. Version 0.1
# =============================================================================
# Nonlinear programming algorithms as the (un-)constrained minimization
# problems with the focus on their numerical expression using various
# programming languages.
#
# This is the Hooke and Jeeves nonlinear unconstrained minimization algorithm.
# =============================================================================
# Copyright (C) 2015 Radislav (Radic) Golubtsov

declare -r EXIT_FAILURE=1 # Failing exit status.
declare -r EXIT_SUCCESS=0 # Successful exit status.

declare -r JAVA=java
declare -r JAVAFLAGS=-cp
declare -r LIB_DIR=lib
declare -r JAR=hooke-jeeves-0.1.jar
declare -r WOODS_CLASS=optimization.nonlinear.unconstrained.core.Woods

${JAVA} ${JAVAFLAGS} ${LIB_DIR}/${JAR} ${WOODS_CLASS}

if [ $? -eq ${EXIT_FAILURE} ]; then
    exit ${EXIT_FAILURE}
fi

exit ${EXIT_SUCCESS}

# =============================================================================
# vim:set nu:et:ts=4:sw=4:
# =============================================================================
